#!/bin/bash

# Git hook used to save permissions of files in the repo.
# Usage: Add this script as a pre-commit hook in the repo pushing the live
#        config. It will generate a permissions database file and add it to
#        the commit. This permissions database file must be used on hosts to
#        restore these file permissions prior to rsyncing them over the
#        target host's live filesystem.
# Author: Omid Ariyan
# Author: Jonathan Gregson <hello@jdgregson.com>
# Source: https://stackoverflow.com/a/38163771

SELF_DIR=`git rev-parse --show-toplevel`
DATABASE=/opt/jdgregson/jdgregson-jupyter-host/permissions

# Clear the permissions database file
> $DATABASE

echo -n "Backing-up permissions..."

IFS_OLD=$IFS; IFS=$'\n'
for FILE in `git ls-files --full-name`
do
   # Save the permissions of all the files in the index
   echo $FILE";"`stat -c "%a;%U;%G" $FILE` >> $DATABASE
done

for DIRECTORY in `git ls-files --full-name | xargs -n 1 dirname | uniq`
do
   # Save the permissions of all the directories in the index
   echo $DIRECTORY";"`stat -c "%a;%U;%G" $DIRECTORY` >> $DATABASE
done
IFS=$IFS_OLD

# Add the permissions database file to the index
git add $DATABASE -f

echo "OK"
